export const GET_OUTPUT_PORTS = "GET_OUTPUT_PORTS";
export const GET_INPUT_PORTS = "GET_INPUT_PORTS";

export const SWITCH_INPUT_DEVICE = "SWITCH_INPUT_DEVICE"
export const SWITCH_OUTPUT_DEVICE = "SWITCH_OUTPUT_DEVICE"


export const RECEIVE_DEVICE_MESSAGE = "RECEIVE_DEVICE_MESSAGE"
export const SEND_DEVICE_MESSAGE = "RECEIVE_DEVICE_MESSAGE"

export const UPDATE_DEVICE = "UPDATE_DEVICE";


export const PLAY_SOUND_FILE = "PLAY_SOUND_FILE"