export const WINDOW_PLACEMENT = "WINDOW_PLACEMENT";

export const SELECTED_MIDI_INPUT_DEVICE = "SELECTED_MIDI_INPUT_DEVICE";
export const SELECTED_MIDI_OUTPUT_DEVICE = "SELECTED_MIDI_OUTPUT_DEVICE";
export const SELECTED_SOUND_OUTPUT_DEVICE = "SELECTED_SOUND_OUTPUT_DEVICE";

export const SELECTED_LAYOUT = "SELECTED_LAYOUT"
export const AVAILABLE_LAYOUTS = "AVAILABLE_LAYOUTS"

export const USE_PUSH_TO_TALK = "USE_PUSH_TO_TALK"
export const PUSH_TO_TALK = "PUSH_TO_TALK"

export const CURRENT_BUTTON_CONFIGURATION = "BUTTON_CONFIGURATION"
export const CURRENT_PAGE = "CURRENT_PAGE"